### ISSUE TITLE
How to create /graphql endpoint

### ISSUE THREAD

**Issue by deone** [Swydo/blaze-apollo-example#1]
Hello!

Thanks for this great Blaze Apollo example. I am trying to expose an endpoint /graphql so I can query the likes from a non-Blaze client. I have tried the example from [here](https://www.apollographql.com/docs/react/recipes/meteor#Server) but it's not working. Any ideas?

**Comment by jamiter** [comment]
What is your client side setup? Make sure you're using an HTTP Apollo Client.

You might want to go to the Meteor forums with more details to ask help there, because you're question is not related to this package. Without giving more details on what is not working it's hard to help.

You can find the forums here: https://forums.meteor.com/

**Comment by deone** [comment]
I would like to just query the GraphQL server with `curl.` Something like this - `curl -X POST -H "Content-Type: application/json" --data '{ "query": "{ people { id name likes } }" }' https://graphql-deone.c9users.io/graphql`
